<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'AK-47 | Asiimov',
                'image_url' => 'img/akruleta.png',
                'price' => 10.00,
                'rarity' => 'legendary',
                'category' => 'rifle',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'M4A4 | Dragon King',
                'image_url' => 'img/m4a4.png',
                'price' => 15.00,
                'rarity' => 'epic',
                'category' => 'rifle',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'AWP | Hyper Beast',
                'image_url' => 'img/awp.png',
                'price' => 20.00,
                'rarity' => 'rare',
                'category' => 'sniper',
                'wear' => 'factory new',
                'status' => 'available',
            ],
            [
                'name' => 'Desert Eagle | Blaze',
                'image_url' => 'img/deagle.png',
                'price' => 8.50,
                'rarity' => 'epic',
                'category' => 'pistol',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'P90 | Death by Kitty',
                'image_url' => 'img/p90.png',
                'price' => 5.00,
                'rarity' => 'common',
                'category' => 'smg',
                'wear' => 'well-worn',
                'status' => 'available',
            ],
            [
                'name' => 'USP-S | Kill Confirmed',
                'image_url' => 'img/usps.png',
                'price' => 12.50,
                'rarity' => 'legendary',
                'category' => 'pistol',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'M4A1-S | Mecha Industries',
                'image_url' => 'img/m4a1.png',
                'price' => 12.50,
                'rarity' => 'rare',
                'category' => 'rifle',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'Glock-18 | Water Elemental',
                'image_url' => 'img/glock.png',
                'price' => 8.00,
                'rarity' => 'common',
                'category' => 'pistol',
                'wear' => 'battle-scarred',
                'status' => 'available',
            ],
            [
                'name' => 'Glock-18 | Emerald Poison Dart',
                'image_url' => 'img/glockSelva.png',
                'price' => 50.00,
                'rarity' => 'legendary',
                'category' => 'pistol',
                'wear' => 'factory new',
                'status' => 'available',
            ],
            [
                'name' => 'Desert Eagle | Conspiracy',
                'image_url' => 'img/deagle.png',
                'price' => 20.00,
                'rarity' => 'epic',
                'category' => 'pistol',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'AUG | Chameleon',
                'image_url' => 'img/aung.png',
                'price' => 35.00,
                'rarity' => 'legendary',
                'category' => 'rifle',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'Karambit | Blue Gem',
                'image_url' => 'img/karambitbluegem.png',
                'price' => 9.50,
                'rarity' => 'rare',
                'category' => 'knife',
                'wear' => 'well-worn',
                'status' => 'available',
            ],
            [
                'name' => 'SSG 08 | Dragonfire',
                'image_url' => 'img/scout.png',
                'price' => 22.00,
                'rarity' => 'epic',
                'category' => 'sniper',
                'wear' => 'factory new',
                'status' => 'available',
            ],
            [
                'name' => 'P90 | Asiimov',
                'image_url' => 'img/howl.png',
                'price' => 7.50,
                'rarity' => 'common',
                'category' => 'smg',
                'wear' => 'battle-scarred',
                'status' => 'available',
            ],
            [
                'name' => 'FAMAS | Pulse',
                'image_url' => 'img/famas.png',
                'price' => 13.00,
                'rarity' => 'rare',
                'category' => 'rifle',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'UMP-45 | Blaze',
                'image_url' => 'img/UMP.png',
                'price' => 6.00,
                'rarity' => 'common',
                'category' => 'smg',
                'wear' => 'well-worn',
                'status' => 'available',
            ],
            [
                'name' => 'Butterfly Knife | Doppler',
                'image_url' => 'img/della.png',
                'price' => 15.00,
                'rarity' => 'legendary',
                'category' => 'knife',
                'wear' => 'factory new',
                'status' => 'available',
            ],
            [
                'name' => 'Bowie Knife | Fade',
                'image_url' => 'img/bowie.png',
                'price' => 25.00,
                'rarity' => 'legendary',
                'category' => 'knife',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'Sport Gloves | Snake Bite',
                'image_url' => 'img/guante-piel.png',
                'price' => 8.00,
                'rarity' => 'legendary',
                'category' => 'gloves',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'Specialist Gloves | Emerald Web',
                'image_url' => 'img/gtortuga.png',
                'price' => 12.00,
                'rarity' => 'legendary',
                'category' => 'gloves',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'Driver Gloves | Butterfly',
                'image_url' => 'img/gbutter.png',
                'price' => 14.50,
                'rarity' => 'legendary',
                'category' => 'gloves',
                'wear' => 'factory new',
                'status' => 'available',
            ],
            [
                'name' => 'Bowie Knife | Crimson Web',
                'image_url' => 'img/bowie-red.png',
                'price' => 22.00,
                'rarity' => 'legendary',
                'category' => 'knife',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'Sport Gloves | Tiger Strike',
                'image_url' => 'img/gtigre.png',
                'price' => 16.50,
                'rarity' => 'legendary',
                'category' => 'gloves',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'Tec-9 | Blood Tiger',
                'image_url' => 'img/tec-red.png',
                'price' => 8.50,
                'rarity' => 'common',
                'category' => 'pistol',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'Tec-9 | Tornado',
                'image_url' => 'img/tec-tornado.png',
                'price' => 10.75,
                'rarity' => 'common',
                'category' => 'pistol',
                'wear' => 'battle-scarred',
                'status' => 'available',
            ],
            [
                'name' => 'FAMAS | Night Bringer',
                'image_url' => 'img/famasdark.png',
                'price' => 15.25,
                'rarity' => 'epic',
                'category' => 'rifle',
                'wear' => 'factory new',
                'status' => 'available',
            ],
            [
                'name' => 'R8 Revolver | Fade',
                'image_url' => 'img/revolver8.png',
                'price' => 9.75,
                'rarity' => 'rare',
                'category' => 'pistol',
                'wear' => 'minimal wear',
                'status' => 'available',
            ],
            [
                'name' => 'R8 Revolver | Blaze',
                'image_url' => 'img/r8chamas.png',
                'price' => 11.25,
                'rarity' => 'epic',
                'category' => 'pistol',
                'wear' => 'field-tested',
                'status' => 'available',
            ],
            [
                'name' => 'AWP | Neo-Noir',
                'image_url' => 'img/awpurple.png',
                'price' => 30.00,
                'rarity' => 'legendary',
                'category' => 'sniper',
                'wear' => 'factory new',
                'status' => 'available',
            ],
        ];

        foreach ($items as $item) {
            Item::create($item);
        }
    }
}
